name: Droplet deployer

on:
  push:
    branches: [deploy-prod]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repostry
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Start/Restart PM2 server
        env:
          PORT: 3000
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
          ENV: production
        run: |
          cd server
          npm run start:prod
